name: Deploy to Tencent Cloud

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 119.28.143.135
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/influencer-app
          git reset --hard HEAD
          git pull
          sudo chown -R ubuntu:ubuntu frontend/dist
          cd backend
          npm install
          npm run build
          cd ../frontend
          npm install
          npm run build
          sudo chown -R www-data:www-data dist
          cd /home/ubuntu/influencer-app/backend
          pm2 restart influencer-app
